name: Publishing post

on:
  push:
    branches: [master]
  schedule:
    - cron: '0 17 */1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Publishing post
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --pure-lockfile
      - run: DEV_TO=${{secrets.DEVTO_API_TOKEN}} yarn run publish:post
      - run: |
          git config user.name michaelcade
          git config user.email michael.cade@outlook.com
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Add dev.to link to last post"
          git push origin master
